name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci

      # Generate Prisma Client (nếu code import client khi build)
      - name: Prisma generate
        run: npx prisma generate

      # Type check
      - name: Type check
        run: npm run -s typecheck || npx tsc --noEmit

      # Lint
      - name: Lint
        run: npm run -s lint || npx eslint . --max-warnings=0

      # Test build (không deploy)
      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
